title: Shreyder93's Data Science Portfolio
description: Health Data Science, Computational Neuroinformatics, and Research Projects
theme: minima  # or any theme you prefer
url: "https://shreyder93.github.io"
